const mongoose = require("mongoose");

const AiPredictionsSchema = new mongoose.Schema({
  Risk: String,
  Issues: String,
  Forecasted_Cost: Number,
  Forecasted_Deviation: Number,
  Burnout_Risk: Number,
});

const SourceDataSchema = new mongoose.Schema({
  Program: String,
  Portfolio: String,
  Project_Manager: String,
  Vendor: String,
  Contract_ID: String,
  Contract_Start_Date: String,
  Contract_End_Date: String,
  Contract_Ceiling_Price: String,
  Contract_Target_Price: String,
  Actual_Contract_Spend: String,
  Expiring_Soon: String,
  Resource_Name: String,
  Role: String,
  Allocated_Hours: String,
  Actual_Hours: String,
  Planned_Cost: String,
  Actual_Cost: String,
  Update_Date: String,
  Project: String,
  Burnout_Risk_Percent: String,
  EV_Percent: String,
  PV_Percent: String,
  AC_Dollar: String,
  CPI: String,
  SPI: String,
  Forecasted_Cost: String,
  Forecast_Deviation: String,
  Variance_at_Completion: String,
  Project_Status_RAG: String,
  Milestone_Status: String,
  Risks: String,
  Issues: String,
  Data_Source: String,
  Dependency_Type: String,
  Impacted_Dashboard: String,
});

const ProjectModelSchema = new mongoose.Schema(
  {
    row_index: Number,
    spreadsheet_id: String,
    ai_predictions: AiPredictionsSchema,
    last_processed_at: Date,
    project_identifier: String,
    source_data: SourceDataSchema,
    sync_timestamp: Date,
    userId: { type: mongoose.Schema.Types.ObjectId, ref: "user" },
  },
  { collection: "GoogleSheet" }
);

// ProjectModelSchema.index({
//   "source_data.Project": "text",
//   "source_data.Program": "text",
//   "source_data.Portfolio": "text",
//   "source_data.Project_Manager": "text",
//   "source_data.Vendor": "text",
//   "source_data.Contract_ID": "text",
//   "source_data.Risks": "text",
//   "source_data.Issues": "text",
// });
ProjectModelSchema.index({
  row_index: "text",
  spreadsheet_id: "text",
  "ai_predictions.Risk": "text",
  "ai_predictions.Issues": "text",
  "ai_predictions.Forecasted_Cost": "text",
  "ai_predictions.Forecasted_Deviation": "text",
  "ai_predictions.Burnout_Risk": "text",

  "source_data.Program": "text",
  "source_data.Portfolio": "text",
  "source_data.Project_Manager": "text",
  "source_data.Vendor": "text",
  "source_data.Contract_ID": "text",
  "source_data.Contract_Start_Date": "text",
  "source_data.Contract_End_Date": "text",
  "source_data.Contract_Ceiling_Price": "text",
  "source_data.Contract_Target_Price": "text",
  "source_data.Actual_Contract_Spend": "text",
  "source_data.Expiring_Soon": "text",
  "source_data.Resource_Name": "text",
  "source_data.Role": "text",
  "source_data.Allocated_Hours": "text",
  "source_data.Actual_Hours": "text",
  "source_data.Planned_Cost": "text",
  "source_data.Actual_Cost": "text",
  "source_data.Update_Date": "text",
  "source_data.Project": "text",
  "source_data.Burnout_Risk_Percent": "text",
  "source_data.EV_Percent": "text",
  "source_data.PV_Percent": "text",
  "source_data.AC_Dollar": "text",
  "source_data.CPI": "text",
  "source_data.SPI": "text",
  "source_data.Forecasted_Cost": "text",
  "source_data.Forecast_Deviation": "text",
  "source_data.Variance_at_Completion": "text",
  "source_data.Project_Status_RAG": "text",
  "source_data.Milestone_Status": "text",
  "source_data.Risks": "text",
  "source_data.Issues": "text",
  "source_data.Data_Source": "text",
  "source_data.Dependency_Type": "text",
  "source_data.Impacted_Dashboard": "text",

  project_identifier: "text",

});

module.exports = mongoose.model("GoogleSheet", ProjectModelSchema);
